default["condor"]["condoruser"] = "condor"
default["condor"]["installdir"] = "/opt"
default["condor"]["compressedfilename"] = "condor"
default["condor"]["condormaster"] = "master"
default["condor"]["condordomain"] = "demo.org"
default["condor"]["masterip"] = "127.0.1.1"
