run: compile
	mpiexec -wdir ${HOME} -n 8 -f machinefile /<%= @shareddir %>/mpi_hello
compile:
	mpicc mpi_hello.c -o /<%= @shareddir %>/mpi_hello
clean:
	rm -rf mpi_hello
python:
	mpiexec -n 8 -f machinefile python /<%= @shareddir %>/helloworld.py
